/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int G(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int G_alloc_mem(void);
int G_init_mem(int mem);
void G_free_mem(int mem);
int G_checkout(void);
void G_release(int mem);
void G_incref(void);
void G_decref(void);
casadi_int G_n_in(void);
casadi_int G_n_out(void);
casadi_real G_default_in(casadi_int i);
const char* G_name_in(casadi_int i);
const char* G_name_out(casadi_int i);
const casadi_int* G_sparsity_in(casadi_int i);
const casadi_int* G_sparsity_out(casadi_int i);
int G_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define G_SZ_ARG 1
#define G_SZ_RES 1
#define G_SZ_IW 0
#define G_SZ_W 91
#ifdef __cplusplus
} /* extern "C" */
#endif
